---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'SNS Alert topic'
# Metadata:
#   'AWS::CloudFormation::Interface':
#     ParameterGroups:
#     - Label:
#         default: 'Alert Parameters'
#       Parameters:
#       - Email
# Parameters:
#   Email:
#     Description: 'Email address that will receive alerts'
#     Type: String
#     Default: ''
Resources:
  Topic:
    Type: 'AWS::SNS::Topic'
    # Properties:
    #   DisplayName: %%SGNAME%%-sns-devops
      # Subscription:
      # - Endpoint: !Ref Email
      #   Protocol: email
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  TopicARN:
    Description: 'The ARN of the alert topic.'
    Value: !Ref Topic
    Export:
      Name: !Sub '${AWS::StackName}-TopicARN'
