AWSTemplateFormatVersion: '2010-09-09'
Description: Hosted Zone for Applications

##################################
# This script creates an Route 53 Hosted Zone
##################################

Parameters:
  pZoneName:
    Type: String
    Default: app
    Description: The name of the hosted zone.

Resources:
  rHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: Hosted Zone for EPT Applications
      HostedZoneTags:
        - Key: Owner
          Value: davemm
      Name: !Ref pZoneName
      VPCs:
        - VPCId: !ImportValue %%VPCNAME%%:vpc-id
          VPCRegion: !ImportValue %%VPCNAME%%:vpc-region
  rDHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: app
      DomainNameServers:
        - AmazonProvidedDNS
      Tags:
        - Key: Name
          Value: !Join [ ":", [ !Ref "AWS::StackName", dhcp-options ] ]
  rVPCDHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: !Ref rDHCPOptions
      VpcId: !ImportValue %%VPCNAME%%:vpc-id
    DependsOn:
      - rDHCPOptions

Outputs:
    oHostedZone:
      Value: !Ref rHostedZone
      Export:
        Name: !Join [ ":", [ !Ref "AWS::StackName", hosted-zone ] ]

    oZoneName:
      Value: !Ref pZoneName
      Export:
        Name: !Join [ ":", [ !Ref "AWS::StackName", name ] ]
